console.log("Buenos dias/ Español")
console.log("Good morning/Ingles")
console.log("Bon Dia/Catalan")
console.log("Bonjour/Frances")
console.log("Buon Giorno/Italiano")
console.log("Bom día/Portugues")
console.log("Guten Tag/Aleman")
console.log(" God morgon/Sueco")
console.log("Dzien dobry/Polaco")
console.log("Dobré ráno/Checo")